import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma.service';
import { Project } from '@prisma/client';
import * as fs from 'fs/promises';
import * as path from 'path';

@Injectable()
export class ProjectsService {
  constructor(private prisma: PrismaService) {}

  async findAllForUser(userId: string): Promise<Project[]> {
    const assignments = await this.prisma.projectAssignment.findMany({
      where: { userId },
      include: { project: true },
    });
    return assignments.map((a) => a.project);
  }

  async findOne(id: string): Promise<Project> {
    const project = await this.prisma.project.findUnique({
      where: { id },
    });
    if (!project) throw new NotFoundException('Project not found');
    return project;
  }

  async findAll(): Promise<Project[]> {
    return this.prisma.project.findMany();
  }

  async create(data: { name: string; hostPath: string; description?: string }) {
    // Ensure the directory exists
    try {
      await fs.mkdir(data.hostPath, { recursive: true });
      
      // Create boilerplate app.js
      const boilerplate = `/**
 * Project: ${data.name}
 * Description: ${data.description || 'Secure Sandbox Environment'}
 * Generated by: BSCS Admin Command Center
 */

console.log("-----------------------------------------");
console.log("🚀 Initializing ${data.name}...");
console.log("🔒 Environment: Secure Isolated Sandbox");
console.log("-----------------------------------------");

// Start your development here...
`;
      await fs.writeFile(path.join(data.hostPath, 'app.js'), boilerplate);
    } catch (err) {
      console.error('Failed to initialize project directory', err);
    }
    
    return this.prisma.project.create({
      data,
    });
  }

  async update(id: string, data: { name?: string; hostPath?: string; description?: string }) {
    return this.prisma.project.update({
      where: { id },
      data,
    });
  }

  async remove(id: string) {
    await this.prisma.projectAssignment.deleteMany({
      where: { projectId: id },
    });
    return this.prisma.project.delete({
      where: { id },
    });
  }

  async assignUser(projectId: string, userId: string) {
    const existing = await this.prisma.projectAssignment.findUnique({
      where: {
        userId_projectId: { userId, projectId }
      }
    });
    if (existing) return existing;
    return this.prisma.projectAssignment.create({
      data: { projectId, userId },
    });
  }
}
